---
apiVersion: v1
kind: Namespace
metadata:
  name: prodapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dj
  namespace: prodapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dj
      version: v1
  template:
    metadata:
      labels:
        app: dj
        version: v1
    spec:
      containers:
        - name: dj
          image: "672518094988.dkr.ecr.us-west-2.amazonaws.com/hello-world:v1.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: "HW_RESPONSE"
              value: "DJ Reporting for duty!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rock-v1
  namespace: prodapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rock
      version: v1
  template:
    metadata:
      labels:
        app: rock
        version: v1
    spec:
      containers:
        - name: rock
          image: "672518094988.dkr.ecr.us-west-2.amazonaws.com/hello-world:v1.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: "HW_RESPONSE"
              value: "[\"Rolling Stones\",\"Aerosmith\"]"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-v1
  namespace: prodapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: country
      version: v1
  template:
    metadata:
      labels:
        app: country
        version: v1
    spec:
      containers:
        - name: country
          image: "672518094988.dkr.ecr.us-west-2.amazonaws.com/hello-world:v1.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: "HW_RESPONSE"
              value: "[\"Johnny Cash\",\"Garth Brooks\"]"
---
apiVersion: v1
kind: Service
metadata:
  name: dj
  namespace: prodapp
  labels:
    app: dj
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: dj
---
apiVersion: v1
kind: Service
metadata:
  name: rock-v1
  namespace: prodapp
  labels:
    app: rock
    version: v1
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: rock
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: country-v1
  namespace: prodapp
  labels:
    app: country
    version: v1
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: country
    version: v1
---
