---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: rock-router
  namespace: prodapp
spec:
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  routes:
    - name: rock-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: rock-v1
              weight: 100
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: country-router
  namespace: prodapp
spec:
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  routes:
    - name: country-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: country-v1
              weight: 100