
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: dj
  namespace: prodapp
spec:
  podSelector:
    matchLabels:
      app: dj
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  backends:
    - virtualService:
        virtualServiceRef:
          name: country
    - virtualService:
        virtualServiceRef:
          name: rock
  serviceDiscovery:
    dns:
      hostname: dj.prodapp.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: country-v1
  namespace: prodapp
spec:
  podSelector:
    matchLabels:
      app: country
      version: v1
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostname: country-v1.prodapp.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: rock-v1
  namespace: prodapp
spec:
  podSelector:
    matchLabels:
      app: rock
      version: v1
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostname: rock-v1.prodapp.svc.cluster.local
