##This file contains the 50/50 weighted test of version 2
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: country-router
  namespace: prodapp
spec:
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  routes:
    - name: country-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: country-v1
              weight: 50
            - virtualNodeRef:
                name: country-v2
              weight: 50 
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: rock-router
  namespace: prodapp
spec:
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  routes:
    - name: rock-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: rock-v1
              weight: 50
            - virtualNodeRef:
                name: rock-v2
              weight: 50 
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: country-v2
  namespace: prodapp
spec:
  podSelector:
    matchLabels:
      app: country
      version: v2
  listeners:
    - portMapping:
        port: 9080
        protocol: http
      healthCheck:
        protocol: http
        path: '/ping'
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 20000
  serviceDiscovery:
    dns:
      hostname: country-v2.prodapp.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: rock-v2
  namespace: prodapp
spec:
  podSelector:
    matchLabels:
      app: rock
      version: v2
  listeners:
    - portMapping:
        port: 9080
        protocol: http
      healthCheck:
        protocol: http
        path: '/ping'
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 20000
  serviceDiscovery:
    dns:
      hostname: rock-v2.prodapp.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-v2
  namespace: prodapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: country
      version: v2
  template:
    metadata:
      labels:
        app: country
        version: v2
    spec:
      containers:
        - name: country
          image: "6722018094988.dkr.ecr.us-west-2.amazonaws.com/hello-world:v1.0"
          ports:
            - containerPort: 9080
          env:
            - name: "HW_RESPONSE"
              value: "[\"Johnny Cash (Kingsland, Arkansas)\",\"Garth Brooks (Tulsa, Oklahoma)\"]"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rock-v2
  namespace: prodapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rock
      version: v2
  template:
    metadata:
      labels:
        app: rock
        version: v2
    spec:
      containers:
        - name: rock
          image: "6722018094988.dkr.ecr.us-west-2.amazonaws.com/hello-world:v1.0"
          ports:
            - containerPort: 9080
          env:
            - name: "HW_RESPONSE"
              value: "[\"Rolling Stones (London, England)\",\"Aerosmith (Boston, Massachusetts)\"]"

---
apiVersion: v1
kind: Service
metadata:
  name: country-v2
  namespace: prodapp
  labels:
    app: country
    version: v2
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: country
    version: v2
---
apiVersion: v1
kind: Service
metadata:
  name: rock-v2
  namespace: prodapp
  labels:
    app: rock
    version: v2
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: rock
    version: v2
---
