apiVersion: v1
kind: Service
metadata:
  name: x-ray-sample-front-k8s
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: x-ray-sample-front-k8s
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-ray-sample-front-k8s
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: x-ray-sample-front-k8s
      tier: frontend
  template:
    metadata:
      labels:
        app: x-ray-sample-front-k8s
        tier: frontend
    spec:
      containers:
        - name: x-ray-sample-front-k8s
          image: 463572477754.dkr.ecr.us-west-2.amazonaws.com/awstc:xray-frontend
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
